package com.kpn.opib.bam.model;

public enum FunctionalProductType {

	HARDWARE_POSTAL, LOCATION_ACCESS, INTERNET_ACCESS, IP_ADD_BLOCK, PINNEN_O_IP, ALARM_O_IP, BACKUP_CONN, ALARMERING_MONIT, EQUIP_MGMT, MULTI_VOICE, PHONE_NUM_BLOCK, VOICE_FEAT_EXTRA, ENGINEER, EMAIL_SWOL, DOMAIN_NAME, WEB_HOSTING, BACK_UP_ONLINE, MULTI_VOICE_ACCESS, PORTING_SYNC, SWOL_PACKAGE

}
