package com.kpn.opib.bam.model;

public enum FunctionalProductStatus {

	SNI_PROVISIONED, COM_ERROR, CANCELLED_CRM, SNI_CANCELLED, PORTING_SYNC, RETRY_SENT, SNI_IN_PROC, SNI_REJECT, CANCELLED_CRM_AFPROV, PLN_RECD, COM_IN_PROC, SNI_ERROR, SNI_CANCELLED_BY_COM, PLN_COMPLETE, SNI_TIMEOUT, NOT_REQUESTED, CANCELLED_CRM_DUPROV, WAIT_PORTING_SYNC, TECH_ERROR, INITIAL, SENT_TO_SNI, PORT_ANS_RECD

}
